# Generated by Django 5.1.7 on 2025-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('mammal', 'ძუძუმწოვარი'), ('bird', 'ფრინველი'), ('reptile', 'რეპტილია'), ('fish', 'თევზი'), ('insect', 'მწერი')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6),
        ),
    ]
